<template>
  <div class="admin-resource">
    <div class="header">
      <h1>Add New Resource</h1>
      <p class="text-muted">Add mental wellness resources to the database</p>
    </div>

    <!-- Success/Error Message -->
    <div v-if="message" :class="['alert', messageType === 'success' ? 'alert-success' : 'alert-danger']">
      {{ message }}
    </div>

    <form @submit.prevent="saveResource" class="resource-form">
      <!-- Resource Type -->
      <div class="form-group">
        <label>Resource Type *</label>
        <select v-model="form.type" class="form-control" required>
          <option value="">Select type</option>
          <option value="video">Video</option>
          <option value="article">Article</option>
          <option value="podcast">Podcast</option>
          <option value="website">Website</option>
          <option value="game">Game</option>
        </select>
      </div>

      <!-- Title -->
      <div class="form-group">
        <label>Title *</label>
        <input type="text" v-model="form.title" class="form-control" required>
      </div>

      <!-- URL -->
      <div class="form-group">
        <label>URL *</label>
        <input type="url" v-model="form.url" class="form-control" placeholder="https://..." required>
      </div>

      <!-- Verified Checkbox -->
      <div class="form-check mb-3">
        <input type="checkbox" v-model="form.is_verified" class="form-check-input" id="verified">
        <label class="form-check-label" for="verified">Verified Resource</label>
      </div>

      <!-- Submit Buttons -->
      <div class="form-actions">
        <button type="submit" class="btn btn-primary" :disabled="loading">
          <span v-if="loading" class="spinner-border spinner-border-sm me-2"></span>
          {{ loading ? 'Saving...' : 'Save Resource' }}
        </button>
        <button type="button" class="btn btn-secondary" @click="resetForm">
          Clear Form
        </button>
      </div>
    </form>
  </div>
</template>

<script>
export default {
  name: 'AdminResource',
  data() {
    return {
      loading: false,
      message: '',
      messageType: 'success',
      form: {
        type: '',
        title: '',
        url: '',
        is_verified: false
        // added_by_admin_id will be null in database
        // created_at will be auto-generated by database
      }
    }
  },
  methods: {
    async saveResource() {
      this.loading = true
      this.message = ''

      // Prepare the data - only what your table has
      const resourceData = {
        type: this.form.type,
        title: this.form.title,
        url: this.form.url,
        is_verified: this.form.is_verified ? 1 : 0
        // added_by_admin_id is omitted - will be NULL in database
        // created_at is omitted - database will auto-generate
      }

      try {
        const response = await fetch('http://127.0.0.1:5000/api/admin/resources', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(resourceData)
        })

        const result = await response.json()

        if (response.ok) {
          this.message = 'Resource added successfully!'
          this.messageType = 'success'
          this.resetForm()
        } else {
          this.message = result.message || 'Error adding resource'
          this.messageType = 'error'
        }
      } catch (error) {
        this.message = 'Network error. Please check if backend is running on port 5000'
        this.messageType = 'error'
        console.error('Error:', error)
      } finally {
        this.loading = false
        
        setTimeout(() => {
          this.message = ''
        }, 5000)
      }
    },

    resetForm() {
      this.form = {
        type: '',
        title: '',
        url: '',
        is_verified: false
      }
    }
  }
}
</script>

<style scoped>
.admin-resource {
  max-width: 600px;
  margin: 40px auto;
  padding: 20px;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

.header {
  margin-bottom: 30px;
}

.header h1 {
  color: #1e293b;
  font-size: 2rem;
  margin-bottom: 10px;
}

.resource-form {
  background: white;
  padding: 30px;
  border-radius: 12px;
  box-shadow: 0 2px 10px rgba(0,0,0,0.1);
}

.form-group {
  margin-bottom: 20px;
}

.form-group label {
  display: block;
  margin-bottom: 8px;
  color: #475569;
  font-weight: 500;
}

.form-control {
  width: 100%;
  padding: 10px 12px;
  border: 2px solid #e2e8f0;
  border-radius: 8px;
  font-size: 1rem;
  transition: border-color 0.3s;
}

.form-control:focus {
  outline: none;
  border-color: #6366f1;
}

.form-check {
  margin-bottom: 15px;
}

.form-check-input {
  margin-right: 8px;
  cursor: pointer;
}

.form-check-label {
  color: #475569;
  cursor: pointer;
}

.form-actions {
  display: flex;
  gap: 15px;
  margin-top: 30px;
}

.btn {
  padding: 12px 24px;
  border: none;
  border-radius: 8px;
  font-size: 1rem;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.3s;
}

.btn-primary {
  background: #6366f1;
  color: white;
  flex: 1;
}

.btn-primary:hover:not(:disabled) {
  background: #4f46e5;
}

.btn-primary:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.btn-secondary {
  background: #e2e8f0;
  color: #475569;
}

.btn-secondary:hover {
  background: #cbd5e1;
}

.alert {
  padding: 15px;
  border-radius: 8px;
  margin-bottom: 20px;
  font-weight: 500;
}

.alert-success {
  background: #dcfce7;
  color: #166534;
  border: 1px solid #86efac;
}

.alert-danger {
  background: #fee2e2;
  color: #991b1b;
  border: 1px solid #fecaca;
}

.text-muted {
  color: #64748b;
  font-size: 0.875rem;
  margin-top: 5px;
  display: block;
}

.spinner-border {
  width: 1rem;
  height: 1rem;
  border-width: 0.15em;
}

@media (max-width: 768px) {
  .admin-resource {
    padding: 10px;
  }
  
  .resource-form {
    padding: 20px;
  }
  
  .form-actions {
    flex-direction: column;
  }
}
</style>